### ISSUE TITLE
test and validate operator heatmap shinny 

### ISSUE THREAD

**Issue by marionlibouban** [tercen/shiny_operator2#2]

**Comment by marionlibouban** [comment]
is it validated?

**Comment by marionlibouban** [comment]
@agouy : faris has comments for you

**Comment by fnaji** [comment]
i will open an issue with alex to modify the shiny heatmap

**Comment by marionlibouban** [comment]
@fnaji : we cannot see the issue you mention can you post it again? or point to it?
